version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: uno_mongo
    command:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:alpine
    container_name: uno_redis
    ports:
      - "6379:6379"
    networks:
      - uno_network
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 50

volumes:
  mongo_data:
networks:
  uno_network:
